name: HubMenu
main: com.buzzyog.hubmenu.Main
version: 1.0
author: BuzzyOG
softdepend: [Votifier, EchoPets]
commands:
  shops:
     description: Main COmmand
     usage: /shops
  credits:
     description: Main COmmand
     usage: /credits
  menu:
     description: Main COmmand
     usage: /menu
