name: GSquadHub
main: com.buzzyog.gsquad.hub.Main
version: 1.0
author: BuzzyOG
softdepend: [Votifier]
commands:
  dev:
     description: Main COmmand
     usage: /dev
  gsquad:
     description: Mainww COmmand
     usage: /gsquad
  
